FROM node:22-bullseye

# Instalación de Chromium
RUN apt-get update && apt-get install -y chromium \
  --no-install-recommends && rm -rf /var/lib/apt/lists/*

# Variable de entornao para que las herramientas de testing encuentren Chromium
ENV CHROME_BIN=/usr/bin/chromium

# Directorio de trabajo
WORKDIR /app

# Instala dependencias y corre los tests de Vitest
CMD ["sh", "-c", "npm install && npm run test"]

